#!/usr/bin/env bash
# A Bash script that gets an Apache server to run on a web server and ensures that it returns a page containing a "Hello Holberton" when querying the root of it.
#
# The reason why the code commented below did not work is because, when Docker containers are installed on different web servers, they have different container IDs
sudo service apache2 start
